apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /image-comments(/|$)(.*)
            backend:
              serviceName: image-comments-service
              servicePort: 8001
          - path: /image-handler(/|$)(.*)
            backend:
              serviceName: image-handler-service
              servicePort: 8000
