apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: image-handler-service
          servicePort: 8000
        path: /image-handler(/|$)(.*)
      - backend:
          serviceName: image-comments-service
          servicePort: 8001
        path: /image-comments(/|$)(.*)
      - backend:
          serviceName: image-upload-service
          servicePort: 8002
        path: /image-upload(/|$)(.*)
      - backend:
          serviceName: image-sharing-service
          servicePort: 8003
        path: /image-sharing(/|$)(.*)
      - backend:
          serviceName: user-handler-service
          servicePort: 8004
        path: /user-handler(/|$)(.*)
      - backend:
          serviceName: image-frontend-service
          servicePort: 80
        path: /()(.*)
